In [ ]:
!apt-get install python3.8.10
!ln -sf /usr/bin/python3.8 /usr/bin/python3

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.8.10
E: Couldn't find any package by glob 'python3.8.10'
E: Couldn't find any package by regex 'python3.8.10'


In [ ]:
!python3 --version

Python 3.8.18


In [ ]:
import re
#str = input("Type word: ")
str = "hello world in research @paula"
for i in ["hello", "world", "@[w]"]:
  str = re.sub(i, "", str, flags=re.IGNORECASE)

str = re.sub(r'(\s)?@\w+', r'\1', str)
str

'  in research '

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
# import these modules
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

print("rocks :", lemmatizer.lemmatize("rocks"))
print("corpora :", lemmatizer.lemmatize("corpora"))

# a denotes adjective in "pos"
print("better :", lemmatizer.lemmatize("better", pos ="a"))

rocks : rock
corpora : corpus
better : good


In [ ]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
english_stopwords = ["is","are"]
sentence = "mangoes are my world"

tokens = sentence.split()

tokens = [token for token in tokens if token.lower() not in english_stopwords]

for i in range(len(tokens)):
  tokens[i] = lemmatizer.lemmatize(tokens[i])

tokens.remove("my")

cleaned_sentence = " ".join(tokens)
cleaned_sentence

'mango world'

In [ ]:
import gensim
from gensim.models import word2vec
from gensim.models.word2vec import Word2Vec
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import spacy
import string
import re

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

#data = pd.read_csv("/content/drive/MyDrive/MSc_study/Summer_2024/man_try1_sec.csv",error_bad_lines=False, engine="python")
data = pd.read_csv("/content/drive/MyDrive/MSc_study/Fall_2023/final_plan_dataset.csv",error_bad_lines=False, engine="python")
#data = pd.read_csv("/content/drive/MyDrive/MSc_study/Fall_2023/2final_plan_dataset.csv",error_bad_lines=False, engine="python")
data.head()

<ipython-input-32-09e7f91dccd0>:4: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  data = pd.read_csv("/content/drive/MyDrive/MSc_study/Fall_2023/4final_plan_dataset.csv",error_bad_lines=False, engine="python")


Unnamed: 0                                               Body  OT  \
0           0  Other than the two issues I opened (map change...   0   
1           1                                How to run the app?   0   
2           2  Hello, First disable SIP on your machine by fo...   0   
3           3            Wow great work, I appreciate your work.   1   
4           4                                         Thank you!   1   

   raf_PLAN  PLAN  
0         1     1  
1         0     1  
2         1     1  
3         1     0  
4         0     0

In [ ]:
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
st_nir = []
dt = pd.read_csv("/content/drive/MyDrive/MSc_study/Fall_2023/smart_stop_words.csv")

for i in range(dt['Column1'].size):
  st_nir.append(dt['Column1'][i])
print(st_nir)

for i in range(dt['Column2'].size):
  st_nir.append(dt['Column2'][i])

for i in range(dt['Column3'].size):
  st_nir.append(dt['Column3'][i])

for i in range(dt['Column4'].size):
  st_nir.append(dt['Column4'][i])

for i in range(dt['Column5'].size):
  st_nir.append(dt['Column5'][i])

for i in range(dt['Column6'].size):
  st_nir.append(dt['Column6'][i])


['a', "a's", 'able', 'about', 'above', 'according', 'accordingly', 'across', 'actually', 'after', 'afterwards', 'again', 'against', "ain't", 'all', 'allow', 'allows', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'an', 'and', 'another', 'any', 'anybody', 'anyhow', 'anyone', 'anything', 'anyway', 'anyways', 'anywhere', 'apart', 'appear', 'appreciate', 'appropriate', 'are', "aren't", 'around', 'as', 'aside', 'ask', 'asking', 'associated', 'at', 'available', 'away', 'awfully', 'b', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'behind', 'being', 'believe', 'below', 'beside', 'besides', 'best', 'better', 'between', 'beyond', 'both', 'brief', 'but', 'by', 'c', "c'mon", "c's", 'came', 'can', "can't", 'cannot', 'cant', 'cause', 'causes', 'certain', 'certainly', 'changes', 'clearly', 'co', 'com', 'come', 'comes', 'concerning', 'consequently', 'consider', 'considering']


In [ ]:
#SE STOP WORDS
#st_nir = []
dt = pd.read_csv("/content/drive/MyDrive/MSc_study/Fall_2023/se_stop_words.csv")

for i in range(dt['stopwords'].size):
  st_nir.append(dt['stopwords'][i])
st_nir

['a',
 "a's",
 'able',
 'about',
 'above',
 'according',
 'accordingly',
 'across',
 'actually',
 'after',
 'afterwards',
 'again',
 'against',
 "ain't",
 'all',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'an',
 'and',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'apart',
 'appear',
 'appreciate',
 'appropriate',
 'are',
 "aren't",
 'around',
 'as',
 'aside',
 'ask',
 'asking',
 'associated',
 'at',
 'available',
 'away',
 'awfully',
 'b',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'believe',
 'below',
 'beside',
 'besides',
 'best',
 'better',
 'between',
 'beyond',
 'both',
 'brief',
 'but',
 'by',
 'c',
 "c'mon",
 "c's",
 'came',
 'can',
 "can't",
 'cannot',
 'cant',
 'cause',
 'causes',
 'certain',
 'certainly',
 'changes',
 'clearly',
 'co',
 'com',
 'come',
 'c

In [ ]:
from nltk.stem import WordNetLemmatizer

corpus = data['Body'].to_list()
lemmatizer = WordNetLemmatizer()
sentence = ""
#len(corpus)
print(corpus[3])

'''
#TRY
sentence = corpus[3]
tokens = sentence.split()
print("STEP 1: ",tokens)
  #tokens = [re.sub([0-9], '', i) for i in tokens]
tokens = [token for token in tokens if token.lower() not in (st_nir or [0-9])]
cleaned_sentence = ""
for j in range(len(tokens)):
  tokens[j] = lemmatizer.lemmatize(tokens[j])
  print("STEP 2: ",tokens[j])
  cleaned_sentence = cleaned_sentence + " " + tokens[j]
  print("STEP 3: ", cleaned_sentence)
  corpus[3] = cleaned_sentence
'''
for i in range(len(corpus)):
  sentence = corpus[i]
  tokens = sentence.split()
  #tokens = [re.sub([0-9], '', i) for i in tokens]
  tokens = [token for token in tokens if token.lower() not in (st_nir or [0-9])]
  cleaned_sentence = ""
  for j in range(len(tokens)):
    tokens[j] = lemmatizer.lemmatize(tokens[j])
    result = re.sub(r'[()\[\]]', '', tokens[j])
    cleaned_sentence = cleaned_sentence + " " + result
    corpus[i] = cleaned_sentence
print(corpus[3])



Wow great work, I appreciate your work.
 Wow great work, work.


In [ ]:
#let's create the vectorizer and fit the corpus and transform them accordingly
v = TfidfVectorizer()
v.fit(corpus)
transform_output = v.transform(corpus)

In [ ]:
transform_output

<3638x15966 sparse matrix of type '<class 'numpy.float64'>'
	with 98335 stored elements in Compressed Sparse Row format>

In [ ]:
print(v.vocabulary_)


{'issue': 7560, 'opened': 9914, 'map': 8615, 'reseting': 11875, 'preference': 10853, 'default': 3896, 'integer': 7335, 'fields': 5478, 'great': 6320, 'mod': 9073, 'good': 6239, 'run': 12210, 'app': 1365, 'hello': 6609, 'sip': 12912, 'machine': 8507, 'tutorial': 14547, 'download': 4469, 'application': 1397, 'link': 8243, 'https': 6823, 'github': 6157, 'com': 3012, 'julian': 7770, 'poidevin': 10693, 'mbpmid2010_gpufix': 8744, 'releases': 11706, 'v0': 14982, 'mbpmid2010': 8743, 'gpu': 6268, 'fix': 5579, 'zip': 15885, 'extract': 5276, 'clock': 2867, 'icon': 6898, 'click': 2849, 'patch': 10319, 'mbp': 8742, 'prompted': 11062, 'warning': 15322, 'message': 8852, 'press': 10905, 'yes': 15803, 'password': 10311, 'request': 11842, 'user': 14932, 'session': 12638, 'wait': 15292, 'process': 10994, 'finished': 5547, 'reboot': 11495, 'computer': 3165, 'done': 4445, 'wow': 15658, 'work': 15613, 'you': 15825, 'job': 7693, 'config': 3225, 'base': 1869, 'sp4': 13155, 'running': 12216, 'obvious': 9736, '

In [ ]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_params',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_tfidf',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',

In [ ]:
#let's print the idf of each word:

all_feature_names = v.get_feature_names_out()

for word in all_feature_names:

    #let's get the index in the vocabulary
    indx = v.vocabulary_.get(word)

    #get the score
    idf_score = v.idf_[indx]

idf_scores = v.idf_

# Create a DataFrame with words and their TF-IDF scores
word_importance_df = pd.DataFrame(list(zip(all_feature_names, idf_scores)), columns=['Word', 'TF-IDF'])

# Sort the DataFrame by TF-IDF score in descending order
word_importance_df = word_importance_df.sort_values(by='TF-IDF', ascending=False)

# Specify the file path where you want to save the CSV file
csv_file_path = "plan_word_importance.csv"

# Save the DataFrame to a CSV file
word_importance_df.to_csv(csv_file_path, index=False)

In [ ]:
#let's print the transformed output from tf-idf
print(transform_output.toarray()[:2])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
#let's print the transformed output from tf-idf
print(transform_output.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
#START FROM HERE - FOR THESIS
import gensim
from gensim.models import word2vec
from gensim.models.word2vec import Word2Vec
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import spacy
import string

from sklearn.model_selection import train_test_split

#df  = pd.read_csv("/content/small_plan_dataset.csv",error_bad_lines=False, engine="python")
#df  = pd.read_csv("/content/bugreport_labeled.csv",error_bad_lines=False, engine="python")
#df1 = pd.read_csv("/content/drive/MyDrive/MSc_study/Summer_2024/man_try1_sec.csv",error_bad_lines=False, engine="python")
df1 = pd.read_csv("/content/drive/MyDrive/MSc_study/Fall_2023/4final_plan_dataset.csv",error_bad_lines=False, engine="python")
df2 = pd.read_csv("/content/drive/MyDrive/MSc_study/Summer_2024/rastkar_bugs_400.csv",error_bad_lines=False, engine="python")
#print(df['COMMENTS'])
'''
X_train = df1['Body']
X_test = df2['Body']
y_train = df1['raf_PLAN']
y_test = df2['PLAN']
'''
X_train = df1['Body']
X_test = df2['Body']
y_train = df1['OT']
y_test = df2['sh_OT']
'''
X_train, X_test, y_train, y_test = train_test_split(
    df.Body,
    df.PLAN,
    test_size=0.2, # 20% samples will go to test dataset
    random_state=2022
)
'''

<ipython-input-36-c61d56faf1bb>:16: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df1 = pd.read_csv("/content/drive/MyDrive/MSc_study/Fall_2023/4final_plan_dataset.csv",error_bad_lines=False, engine="python")
<ipython-input-36-c61d56faf1bb>:17: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df2 = pd.read_csv("/content/drive/MyDrive/MSc_study/Summer_2024/rastkar_bugs_400.csv",error_bad_lines=False, engine="python")


'\nX_train, X_test, y_train, y_test = train_test_split(\n    df.Body,\n    df.PLAN,\n    test_size=0.2, # 20% samples will go to test dataset\n    random_state=2022\n)\n'

In [ ]:
df1 = pd.read_csv("/content/predict_ot.csv",error_bad_lines=False, engine="python")

#print(df1)
#for i in range(2360):
for number in df1:
    print(number)


<ipython-input-15-acdf7cdd8c5a>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df1 = pd.read_csv("/content/predict_ot.csv",error_bad_lines=False, engine="python")


FileNotFoundError: [Errno 2] No such file or directory: '/content/predict_ot.csv'

In [ ]:
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)

Shape of X_train:  (3638,)
Shape of X_test:  (2360,)


In [ ]:
y_train.value_counts()

0    3158
1     480
Name: OT, dtype: int64

In [ ]:
y_test.value_counts()

0    2272
1      88
Name: sh_OT, dtype: int64

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

#1. create a pipeline object
clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),
     ('KNN', KNeighborsClassifier())
])

#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.91      0.95      2272
           1       0.19      0.52      0.28        88

    accuracy                           0.90      2360
   macro avg       0.59      0.72      0.61      2360
weighted avg       0.95      0.90      0.92      2360



In [ ]:
X_test[:5]

960     The window class for this object has been reas...
1566                    The one in text land is bug 88293
2876                            I forgot I could tag here
9              2) form history finds 1 entry (\""blah\"")
1863                                  Thats good to know.
Name: COMMENTS, dtype: object

In [ ]:
y_test[:5]

960     0
1566    0
2876    0
9       0
1863    0
Name: PLAN, dtype: int64

In [ ]:
y_pred[:5]

array([0, 0, 0, 0, 0])

In [ ]:
from sklearn.naive_bayes import MultinomialNB


#1. create a pipeline object
clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),
     ('Multi NB', MultinomialNB())
])

#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1360
           1       0.42      1.00      0.60      1000

    accuracy                           0.42      2360
   macro avg       0.21      0.50      0.30      2360
weighted avg       0.18      0.42      0.25      2360



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn import svm


#1. create a pipeline object
clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),
     ('Multi NB', svm.SVC())
])

#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      2272
           1       0.78      0.28      0.42        88

    accuracy                           0.97      2360
   macro avg       0.88      0.64      0.70      2360
weighted avg       0.97      0.97      0.96      2360



In [ ]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

#1. create a pipeline object
clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),        #using the ngram_range parameter
     ('Random Forest', RandomForestClassifier())
])

#2. fit with X_train and y_train
clf.fit(X_train, y_train)

'''
#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)
print(y_pred)
#my = pd.DataFrame.from_records(y_pred)
my = y_pred.tolist()
for i in range(2360):
  #file1.writelines(my[i])
  print(my[i])
  with open("myfile.txt", "w") as file1:
    file1.writelines(my[0])
'''
'''
with open("myfile.txt", "w") as file1:
    # Writing data to a file
    for i in range(2360):
      file1.writelines(my[i])

with open('predict_ot.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    field = ["SH_LABEL"]
    for i in range(0, 2360):
      me = my[i]
      writer.writerow(me)
'''

# Specify the file path where you want to save the CSV file
csv_file_path2 = "plan_predict.csv"
df = pd.DataFrame(y_pred)
# Save the DataFrame to a CSV file
df.to_csv(csv_file_path2, index=False)

'''
# Import Joblib
import joblib

# Save the model to a file
joblib.dump(clf, 'sh_model_3_8.joblib')

# Load the model using Joblib
loaded_model_joblib = joblib.load('sh_model_3_8.joblib')
'''

import pickle

# Save the model to a file
with open('my_model.pkl', 'wb') as file:
    pickle.dump(clf, file)

with open('my_model.pkl', 'rb') as file:
    loaded_model_pickle = pickle.load(file)

#3. get the predictions for X_test and store it in y_pred
#y_pred = clf.predict(X_test)



y_pred = loaded_model_pickle.predict(X_test)

#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.95      0.97      2272
           1       0.28      0.48      0.35        88

    accuracy                           0.94      2360
   macro avg       0.63      0.72      0.66      2360
weighted avg       0.95      0.94      0.94      2360



In [ ]:
#Pema grg
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pickle
from sklearn import linear_model
#Project_path = "<path to the project folder>"
from sklearn.ensemble import RandomForestClassifier



#2. fit with X_train and y_train
clf.fit(X_train, y_train)

data = pd.read_csv('/content/drive/MyDrive/MSc_study/Fall_2023/4final_plan_dataset.csv',error_bad_lines=False, engine="python")
#print (data.category.unique())
vectorizer = TfidfVectorizer(sublinear_tf=True, encoding='utf-8',
                             decode_error='ignore')


def train_bpsd(df, vectorizer):
    tfidf = vectorizer.fit(df["Body"].values.astype('U'))

    X = vectorizer.fit_transform(df["Body"].values.astype('U'))
    y = df['OT']
    #train_test(X, y)
    model = svm.LinearSVC()

    print("==fitting the model===")
    model.fit(X.A, y)

    print("==fit done\=")
    return model, tfidf


Project_path = "/content/drive/MyDrive/MSc_study"

model_path = Project_path + "/sh_models/sh.pickle"
vectorizer_path = Project_path + "/sh_models/sh_vectorizer.pickle"
model, vectorizer_model = train_bpsd(data, vectorizer)
pickle.dump(model, open(model_path, 'wb'))
pickle.dump(vectorizer_model, open(vectorizer_path, "wb"))


<ipython-input-22-8112232215ba>:17: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  data = pd.read_csv('/content/drive/MyDrive/MSc_study/Fall_2023/4final_plan_dataset.csv',error_bad_lines=False, engine="python")


==fitting the model===
==fit done\=


FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/MSc_study/sh_models/sh.pickle'

In [ ]:
from sklearn import tree

#1. create a pipeline object
clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),
     ('Multi NB', tree.DecisionTreeClassifier())
])

#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.93      0.95      2272
           1       0.16      0.33      0.21        88

    accuracy                           0.91      2360
   macro avg       0.57      0.63      0.58      2360
weighted avg       0.94      0.91      0.92      2360



In [ ]:
import matplotlib.pyplot as plt

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(
    n_samples=1000,
    n_features=10,
    n_informative=3,
    n_redundant=0,
    n_repeated=0,
    n_classes=2,
    random_state=0,
    shuffle=False,
)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42)

from sklearn.ensemble import RandomForestClassifier

feature_names = [f"{X[i]}" for i in range(X.shape[1])]
forest = RandomForestClassifier(random_state=0)
forest.fit(X_train, y_train)

import time

import numpy as np

start_time = time.time()
importances = forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in forest.estimators_], axis=0)
elapsed_time = time.time() - start_time

print(f"Elapsed time to compute the importances: {elapsed_time:.3f} seconds")

import pandas as pd

forest_importances = pd.Series(importances, index=feature_names)

feature_scores = pd.Series(forest.feature_importances_, index=feature_names).sort_values(ascending=False)

feature_scores



Elapsed time to compute the importances: 0.011 seconds


[-0.48628731  2.43254818 -2.81984222 -0.16765617  1.1524328  -0.20515407\n  1.67435428  0.92336623 -0.5970967  -0.78257457]    0.317872
[ 0.24983722  2.07999753 -2.41574285  1.55250219 -0.02025345  1.52308665\n  1.50875967 -0.44983528 -0.04794935 -0.36425081]    0.209443
[ 0.13037419  1.37164964 -1.48661612  0.28419927 -0.27937185  0.48323822\n -1.70331195 -1.31814927 -1.18427125  0.9759933 ]    0.195190
[-0.15204948  1.90934407 -2.7491062  -0.07976561 -0.81365327 -0.14478753\n -0.40902935  0.55462549 -1.08926689 -1.96281359]    0.042573
[-1.59611679  2.13533402 -2.44406814  0.47294311  0.13873703 -1.18721985\n -1.29116116  0.15843627 -0.54466637  0.30312958]    0.041581
[ 0.03665774  0.96342311 -1.6891696  -1.65494387  1.08040923 -0.73978191\n -0.2680128  -0.62612224  1.00035313  1.6443156 ]    0.040393
[ 0.06197247  1.80809251 -1.55423753 -0.3123385  -0.73702997  1.90030652\n  0.15354636  1.28187305 -0.00282095 -0.30701463]    0.040255
[ 0.38317678  1.0920481  -0.76797611 -1.20240135

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

AttributeError: ignored

In [ ]:
from sklearn import svm
import csv

#1. create a pipeline object
clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),        #using the ngram_range parameter
     ('svm', svm.SVC())
])

#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)
#df = pd.DataFrame.from_records(y_pred)
'''
with open('predict_ot.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    field = ["SH_LABEL"]
    writer.writerow(field)
    for i in range(2360):
      writer.writerow(df[i])
'''
#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98      2272
           1       0.34      0.24      0.28        88

    accuracy                           0.95      2360
   macro avg       0.66      0.61      0.63      2360
weighted avg       0.95      0.95      0.95      2360



In [ ]:
x_train = df1['Body']
x_test = df2['Body']
y_train = df1['OT']
y_test = df2['sh_OT']